version: 2
spec_steps: &spec_steps
  - checkout
  - run:
      name: Which bundler?
      command: bundle -v
  - restore_cache:
      keys:
        - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
        - rails-demo-bundle-v2-
  - run:
      name: Bundle Install
      command: bundle check || bundle install
  - save_cache:
      key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  - run:
      name: Wait for Redis
      command: dockerize -wait tcp://localhost:6379 -timeout 1m
  - run:
      name: Run rspec
      command: |
        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out test_results/rspec.xml \
                          --format progress \
                          $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
  - store_test_results:
      path: test_results
jobs:
  ruby-2.5:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
      - image: circleci/redis
    steps:
      *spec_steps
  ruby-2.6:
    docker:
      - image: circleci/ruby:2.6.0
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
      - image: circleci/redis
    steps:
      *spec_steps
workflows:
  version: 2
  build:
    jobs:
      - ruby-2.5
      - ruby-2.6
